import { z } from "zod";

export const createProductSchema = z.object({
  name:        z.string().min(2).max(100).trim(),
  description: z.string().max(2000).trim().optional().default(""),
  price:       z.number({ required_error: "Price is required" }).nonnegative(),
  priceUnit:   z.string().trim().default("Piece"),
  sku:         z.string().trim().optional().default(""),
  minOrderQty: z.number().int().min(1).optional().default(500),
  showInRetail:z.boolean().optional().default(false),
  category:    z.string({ required_error: "Category is required" }).min(1),
  subcategory: z.string().trim().nullable().optional().or(z.literal("")),
  images:      z.array(z.string().url()).min(1, "At least one image is required"),
  productType:     z.string().max(100).trim().optional().default(""),
  primaryMaterial: z.string().max(100).trim().optional().default(""),
  style:           z.string().max(100).trim().optional().default(""),
  setType:         z.string().max(100).trim().optional().default(""),
  color:           z.string().max(100).trim().optional().default(""),
  sizeCategory:    z.string().max(100).trim().optional().default(""),
  theme:           z.string().max(100).trim().optional().default(""),
  usageArea:       z.string().max(200).trim().optional().default(""),
  bestSelling:     z.boolean().optional().default(false),
  newArrival:      z.boolean().optional().default(false),
});

export const updateProductSchema = z.object({
  name:        z.string().min(2).max(100).trim().optional(),
  description: z.string().max(2000).trim().optional(),
  price:       z.number().nonnegative().optional(),
  priceUnit:   z.string().trim().optional(),
  sku:         z.string().trim().optional(),
  minOrderQty: z.number().int().min(1).optional(),
  showInRetail:z.boolean().optional(),
  category:    z.string().min(1).optional(),
  subcategory: z.string().trim().nullable().optional().or(z.literal("")),
  images:      z.array(z.string().url()).min(1).optional(),
  productType:     z.string().max(100).trim().optional(),
  primaryMaterial: z.string().max(100).trim().optional(),
  style:           z.string().max(100).trim().optional(),
  setType:         z.string().max(100).trim().optional(),
  color:           z.string().max(100).trim().optional(),
  sizeCategory:    z.string().max(100).trim().optional(),
  theme:           z.string().max(100).trim().optional(),
  usageArea:       z.string().max(200).trim().optional(),
  bestSelling:     z.boolean().optional(),
  newArrival:      z.boolean().optional(),
});
